### ISSUE TITLE
How to sort by multiple fields?

### ISSUE THREAD

**Issue by medisoft** [Bill4Time/object-property-natural-sort#1]
Hi! I want to know how to do a sort by multiple fields, like sorting by age and height.

Thanks

**Comment by khous** [comment]
Sorry, it's not possible with this function. You can make your own though. If you are just doing `Number` comparisons, you should not use this function which provides a 'natural' sort and instead use the function below. 
```
[{ age: 20, height: 72 }, { age: 30, height: 48 }].sort((a, b) => {
  let comp = a.age - b.age;
  if (comp !== 0} return comp;
  return a.height - b.height;
});
```
